version: "3.7"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - website:/var/www
      - ./config/website_vhost.conf:/etc/nginx/conf.d/default.conf
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - ./config/yourdomain.com.crt:/etc/nginx/certs/yourdomain.com.crt
      # - ./config/yourdomain.com.key:/etc/nginx/certs/yourdomain.com.key
    ports:
      # CHANGE TO "80:80" IF USING NGINX FOR SSL TERMINATION
      - "9080:80"
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - "443:443"

  githugo:
    image: zeigren/githugo:latest
    volumes:
      - website:/git
    # UNCOMMENT IF USING A REPO WITH SSH
      # - ./config/ssh_private:/root/.ssh/id_rsa
      # - ./config/ssh_public:/root/.ssh/id_rsa.pub
      # - ./config/remote_ssh:/root/.ssh/known_hosts
    environment:
      - REPO=LINK_TO_GIT_REPO
      - FOLDER=GIT_REPO_NAME
    deploy:
      restart_policy:
        # UNCOMMENT DELAY AND COMMENT CONDITION IF YOU WANT IT TO PERIODICALLY REBUILD
        condition: none
        # delay: 4h

volumes:
  website:
