version: "3.8"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  nginx:
    image: nginx:alpine
    # https://hub.docker.com/_/nginx
    volumes:
      - website:/var/www
    networks:
      - traefik
    configs:
      - source: website_nginx.conf
        target: /etc/nginx/templates/nginx.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      # https://nginx.org/en/docs/ngx_core_module.html#worker_processes
      - NGINX_WORKER_PROCESSES=auto
      # https://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile
      - NGINX_WORKER_RLIMIT_NOFILE=65535
      # https://nginx.org/en/docs/ngx_core_module.html#worker_connections
      - NGINX_WORKER_CONNECTIONS=65535
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
      - NGINX_CLIENT_MAX_BODY_SIZE=10m
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout
      - NGINX_CLIENT_BODY_TIMEOUT=30s
      - NGINX_HOST=yourdomain.test www.yourdomain.test
      - GIT_REPO_NAME=GIT_REPO_NAME
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bookstack.entrypoints=websecure"
        - "traefik.http.routers.bookstack.rule=Host(`yourdomain.test`, `www.yourdomain.test`)"
        - "traefik.http.services.bookstack.loadbalancer.server.port=80" # Port traefik needs to route traffic to

  githugo:
    image: zeigren/githugo:latest
    # https://hub.docker.com/r/zeigren/githugo
    volumes:
      - website:/git
    # UNCOMMENT IF USING A REPO WITH SSH
    # secrets:
    #   - source: ssh_private
    #     target: /root/.ssh/id_rsa
    #     mode: 0400
    #   - source: ssh_public
    #     target: /root/.ssh/id_rsa.pub
    #     mode: 0444
    #   - source: remote_ssh
    #     target: /root/.ssh/known_hosts
    environment:
      - REPO=LINK_TO_GIT_REPO
      - FOLDER=GIT_REPO_NAME
    deploy:
      restart_policy:
        # UNCOMMENT DELAY AND COMMENT CONDITION IF YOU WANT IT TO PERIODICALLY REBUILD
        condition: none
        # delay: 4h

volumes:
  website:

networks:
  traefik:
    external: true

configs:
  website_nginx.conf:
    external: true
# UNCOMMENT IF USING A REPO WITH SSH
# secrets:
#   ssh_private:
#     external: true
#   ssh_public:
#     external: true
#   remote_ssh:
#     external: true
