version: "3.7"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - website:/var/www
    networks:
      - traefik
    configs:
      - source: website_vhost
        target: /etc/nginx/conf.d/default.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.website-http.entrypoints=web"
        - "traefik.http.routers.website-http.rule=Host(`yourdomain.com`)"
        - "traefik.http.routers.website-http.middlewares=website-https@docker"
        - "traefik.http.routers.website.entrypoints=websecure"
        - "traefik.http.routers.website.rule=Host(`yourdomain.com`)"
        - "traefik.http.routers.website.tls=true"
        - "traefik.http.routers.website.tls.certresolver=myresolver"
        - "traefik.http.services.website.loadbalancer.server.port=80"
        - "traefik.http.middlewares.website-https.redirectscheme.scheme=https"
        # Security
        - "traefik.http.middlewares.website.headers.sslredirect=true"
        - "traefik.http.middlewares.website.headers.stsseconds=315360000"
        - "traefik.http.services.website.loadbalancer.passhostheader=true"
        - "traefik.http.middlewares.website.headers.sslforcehost=true"
        - "traefik.http.middlewares.website.headers.sslhost=website.com"
        - "traefik.http.middlewares.website.headers.browserxssfilter=true"
        - "traefik.http.middlewares.website.headers.contenttypenosniff=true"
        - "traefik.http.middlewares.website.headers.forcestsheader=true"
        - "traefik.http.middlewares.website.headers.stsincludesubdomains=true"
        - "traefik.http.middlewares.website.headers.stspreload=true"
        - "traefik.http.middlewares.website.headers.customFrameOptionsValue=SAMEORIGIN"

  githugo:
    image: zeigren/githugo:latest
    volumes:
      - website:/git
    # UNCOMMENT IF USING A REPO WITH SSH
    # secrets:
    #   - source: ssh_private
    #     target: /root/.ssh/id_rsa
    #     mode: 0400
    #   - source: ssh_public
    #     target: /root/.ssh/id_rsa.pub
    #     mode: 0444
    #   - source: remote_ssh
    #     target: /root/.ssh/known_hosts
    environment:
      - REPO=LINK_TO_GIT_REPO
      - FOLDER=GIT_REPO_NAME
    deploy:
      restart_policy:
        # UNCOMMENT DELAY AND COMMENT CONDITION IF YOU WANT IT TO PERIODICALLY REBUILD
        condition: none
        # delay: 4h

volumes:
  website:

networks:
  traefik:
    external: true

configs:
  website_vhost:
    external: true

# UNCOMMENT IF USING A REPO WITH SSH
# secrets:
#   ssh_private:
#     external: true
#   ssh_public:
#     external: true
#   remote_ssh:
#     external: true
