version: "3.7"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  nginx:
    image: nginx:alpine
    # https://hub.docker.com/_/nginx
    volumes:
      - website:/var/www
      - ./config/website_nginx.conf:/etc/nginx/templates/nginx.conf.template
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - ./config/yourdomain.com.crt:/etc/nginx/certs/yourdomain.com.crt
      # - ./config/yourdomain.com.key:/etc/nginx/certs/yourdomain.com.key
    ports:
      # CHANGE TO "80:80" IF USING NGINX FOR SSL TERMINATION
      - "9080:80"
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - "443:443"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      # https://nginx.org/en/docs/ngx_core_module.html#worker_processes
      - NGINX_WORKER_PROCESSES=auto
      # https://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile
      - NGINX_WORKER_RLIMIT_NOFILE=65535
      # https://nginx.org/en/docs/ngx_core_module.html#worker_connections
      - NGINX_WORKER_CONNECTIONS=65535
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
      - NGINX_CLIENT_MAX_BODY_SIZE=10m
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout
      - NGINX_CLIENT_BODY_TIMEOUT=30s
      - NGINX_HOST=yourdomain.test www.yourdomain.test
      - GIT_REPO_NAME=GIT_REPO_NAME
      # UNCOMMENT IF USING NGINX FOR SSL
      # - NGINX_SSL_CERT=yourdomain.test.crt
      # - NGINX_SSL_KEY=yourdomain.test.key

  githugo:
    image: zeigren/githugo:latest
    # https://hub.docker.com/r/zeigren/githugo
    volumes:
      - website:/git
      # UNCOMMENT IF USING A REPO WITH SSH
      # - ./config/ssh_private:/root/.ssh/id_rsa
      # - ./config/ssh_public:/root/.ssh/id_rsa.pub
      # - ./config/remote_ssh:/root/.ssh/known_hosts
    environment:
      - REPO=LINK_TO_GIT_REPO
      - FOLDER=GIT_REPO_NAME
    deploy:
      restart_policy:
        # UNCOMMENT DELAY AND COMMENT CONDITION IF YOU WANT IT TO PERIODICALLY REBUILD
        condition: none
        # delay: 4h

volumes:
  website:
